// Generated by CoffeeScript 1.7.1
var ImageState, adustPlaceholder, batchImagesDownloadFinished, contentLinksOnClick, downloadAllImages, imageClickToLoad, imageClickToShowLargeImage, loadAllCachedImages, loadAllCachedImagesFinished, pageDidLoad, relatedStocksOnClick, replacePlaceholder, setImagePlaceholderState, showTipAtImagePlaceholder, singleImageDownloadFailed, singleImageDownloadFinished, toggleLargeFonts,moreCommentsOnClick,changeReturnUrl;

ImageState = {
manuallyLoad: "点击可下载",
downLoading: "正在下载",
loadingFailed: "图片下载失败，点击重试",
loadingSuccess: "下载成功"
};

setImagePlaceholderState = function(image_ph_id, state) {
    var image_ph;
    image_ph = $('#' + image_ph_id);
    switch (state) {
        case ImageState.manuallyLoad:
        case ImageState.loadingFailed:
            image_ph.on('click', imageClickToLoad);
            break;
        case ImageState.downLoading:
            image_ph.off();
            break;
        default:
            image_ph.off();
    }
    return showTipAtImagePlaceholder(image_ph_id, state);
};

showTipAtImagePlaceholder = function(imagePlaceholder, imageState) {
    var placeholder;
    console.log('showTipAtImagePlaceholder: ' + imagePlaceholder);
    placeholder = $('#' + imagePlaceholder);
    placeholder.children('.tip').remove();
    if (imageState !== ImageState.downLoading && ImageState.loadingSuccess) {
        return $("<span class=\"tip\">" + imageState + "</span>").appendTo(placeholder);
    }
};

pageDidLoad = function() {
    //  $('.relate-stocks a').on('click', relatedStocksOnClick);
    //    $('article .content-link').on('click', contentLinksOnClick);
    //    $('.news-comments').on('click', moreCommentsOnClick);
    //  adustPlaceholder();
};

adustPlaceholder = function() {
    return $('.image-placeholder-wrap').each(function() {
                                             var $this, actualHeight, actualWidth, originHeight, originWidth;
                                             $this = $(this);
                                             originWidth = $this.attr('origin-width');
                                             originHeight = $this.attr('origin-height');
                                             actualWidth = $this.width();
                                             actualHeight = originHeight / originWidth * actualWidth;
                                             return $this.height(actualHeight);
                                             });
};

replacePlaceholder = function(idx, url) {
    var elem, parent;
    console.log('replacePlaceholder: ' + idx);
    elem = $('#image_ph_' + idx);
    parent = elem.parent();
    elem.remove();
    return $('<img>').attr('src', url).attr('id', 'image_' + idx).addClass('news-image').appendTo(parent).on('click', imageClickToShowLargeImage);
};

relatedStocksOnClick = function() {
    var $this, fullCode, stockName;
    $this = $(this);
    fullCode = $this.attr('stock-code');
    stockName = $this.html();
    return SNJavascriptBridge.callNativeBlock("relatedStocksOnClick", {
                                              "fullCode": fullCode,
                                              "stockName": stockName
                                              });
};

removeImageA = function(){
    var elems = $('.placeholder');
    for (var i = 0; i < elems.length ; i++) {
        var _EmImageRemarkA = elems[i].parentNode;
        if(_EmImageRemarkA.nodeName=='A'){
            _EmImageRemarkA.removeAttribute('href');
        }
    }
}

contentLinksOnClick = function() {
    var $this, url, fullCode, stockName;
    $this = $(this);
    url = $this.attr('url');
    fullCode = $this.attr('fullCode');
    stockName = $this.attr('stockName');
    return SNJavascriptBridge.callNativeBlock("contentLinksOnClick", {
                                              "url": url,
                                              "fullCode": fullCode,
                                              "stockName": stockName
                                              });
};

imageClickToLoad = function() {
    var $this;
    $this = $(this);
    setImagePlaceholderState($this.attr('id'), ImageState.downLoading);
    return SNJavascriptBridge.callNativeBlock("loadImage", {
                                              "url": $this.attr('target-url'),
                                              "id": $this.attr('id')
                                              });
};

imageClickToShowLargeImage = function() {
    var $this, bounds, imageElem, imageId, imageURL;
    $this = $(this);
    imageElem = $this.get(0);
    bounds = null;
    if (imageElem != null) {
        bounds = imageElem.getBoundingClientRect();
        bounds.width = imageElem.width;
        bounds.height = imageElem.height;
    }
    imageId = $this.attr('id');
    imageURL = $this.attr('src');
    return SNJavascriptBridge.callNativeBlock("loadLargeImage", {
                                              "url": imageURL,
                                              "id": imageId,
                                              "bounds": bounds
                                              });
};

downloadAllImages = function() {
    var images, results;
    images = $('.image-placeholder-wrap');
    results = [];
    images.each(function() {
                return results.push({
                                    "url": $(this).attr('target-url'),
                                    "id": $(this).attr('id')
                                    });
                });
    return SNJavascriptBridge.callNativeBlock("batchDownloadImages", {
                                              "images": results
                                              });
};

loadAllCachedImages = function() {
    var images, results;
    images = $('.image-placeholder-wrap');
    results = [];
    images.each(function() {
                return results.push({
                                    "url": $(this).attr('target-url'),
                                    "id": $(this).attr('id')
                                    });
                });
    return SNJavascriptBridge.callNativeBlock("loadAllCachedImages", {
                                              "images": results
                                              });
};

singleImageDownloadFinished = function(imgId, url) {
    var idx;
    console.log('singleImageDownloadFinished: ' + imgId);
    idx = imgId.replace('image_ph_', '');
    replacePlaceholder(idx, url);
    setImagePlaceholderState(imgId, ImageState.loadingSuccess);
    SNJavascriptBridge.callNativeBlock("reloadArticleHeight");
};

singleImageDownloadFailed = function(imgId) {
    setImagePlaceholderState(imgId, ImageState.loadingFailed);
    SNJavascriptBridge.callNativeBlock("reloadArticleHeight");
};

batchImagesDownloadFinished = function(arr) {
    var info, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
        info = arr[_i];
        if ((info['url'] != null) && (info['id'] != null)) {
            if (info['success'] === 1) {
                _results.push(singleImageDownloadFinished(info['id'], info['url']));
            } else {
                _results.push(singleImageDownloadFailed(info['id']));
            }
        } else {
            _results.push(void 0);
        }
    }
    return _results;
};

loadAllCachedImagesFinished = function(arr) {
    var info, _i, _len, _results;
    console.log(arr);
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
        info = arr[_i];
        console.log(info);
        if ((info['url'] != null) && (info['id'] != null)) {
            console.log(info);
            if (info['success'] === 1) {
                _results.push(singleImageDownloadFinished(info['id'], info['url']));
            } else {
                _results.push(setImagePlaceholderState(info['id'], ImageState.manuallyLoad));
            }
        } else {
            _results.push(void 0);
        }
    }
    return _results;
};

setPostTextColor = function(newsColor) {
    var content=document.getElementById('news-article');
    
    var childs=content.getElementsByTagName('p');
    for(var i=0;i<childs.length;i++){
        childs[i].style.color=newsColor;
    }
};

setRelatedStocksColor = function(newsColor) {
    
    var childs=document.getElementsByTagName('a');
    for(var i=0;i<childs.length;i++){
        if(childs[i].className != 'link-stkd' && childs[i].className !='news-comments' && childs[i].className !='wxa' && childs[i].className !='pyqa' && childs[i].className !='wba'){
            childs[i].style.color=newsColor;
        }
    }
    
};

moreCommentsOnClick = function(e) {
    SNJavascriptBridge.callNativeBlock("moreCommentsOnClick");
    return e.preventDefault();
};

toggleLargeFonts = function(largeFont) {
    $('#news-article').css('font-size', largeFont ? '20px' : '17px');
    $('p').css('line-height', largeFont ? '29px' : '26px');
    $('p').css('margin', largeFont ? '0px' : '0px');
    $('.comment-content').css('font-size', largeFont ? '17px' : '14px');
    $('#news-title').css('font-size', largeFont ? '22px' : '18px');
};

initADLinks = function()
{
    var ad_app_src = document.getElementsByName("ad_app_src");
    var _tempLinkUrl = null;
    var _tempLinkHTML = null;
    var isPass;
    for(var _i = 0;_i < ad_app_src.length;_i++){
        _tempLinkUrl = null;
        _tempLinkHTML = null;
        isPass = false;
        _tempLinkUrl = ad_app_src[_i].getAttribute("src_ios");
        _tempLinkHTML = ad_app_src[_i].getAttribute("src_text");
        
        if(isPass || _tempLinkUrl == null){
            continue;
        }
        var _newLink = document.createElement("a");
        _newLink.setAttribute("href",_tempLinkUrl);
        _newLink.innerHTML=_tempLinkHTML;
        ad_app_src[_i].parentNode.insertBefore(_newLink,ad_app_src[_i]);
    }
};

// 这个方法暂时不用了
function doStuff(){
    pageDidLoad();
    
    var _tables = document.getElementsByTagName("table");
    
    for(var i=0;i<_tables.length;i++){
        var _tmpTableBox = document.createElement("div");
        _tmpTableBox.className = "tableBox";
        _tables[i].parentNode.insertBefore(_tmpTableBox, _tables[i]);
        _tmpTableBox.insertBefore(_tables[i]);
        var _tipTxt = document.createElement("div");
        _tipTxt.className = "tableBoxTip";
        _tipTxt.innerHTML = "左右拖动表格，可查看剩余表格内容";
        _tmpTableBox.insertBefore(_tipTxt,_tmpTableBox.firstChild);
    }
};

//设置字体
resetFont = function(bodyfont, titlefont, pfont ,pPadding) {
    $('#news-article').css('font-size', bodyfont);
    $('#relate-stocks').css('font-size', bodyfont);
    $('#news-content').css('font-size', bodyfont);
    $('#news-title').css('font-size', titlefont);
    
    $('p').css('font-size', bodyfont);
    $('p').css('line-height', pfont);
    $('p').css('margin-top', pPadding);
};

//设置图片
resetImage = function(idx, url, base64) {
    var elem, parent;
    elem = $('#image_ph_' + idx);
    parent = elem.parent();
    elem.remove();
    return $('<img>').attr('src', base64).attr('id', 'image_ph_' + idx).attr('imageurl', url).addClass('news-image').appendTo(parent).on('click', showLargeImage);
};

//设置行情图片
resetStockImage = function(idx, url, base64 ,stockindex) {
    var elem, parent;
    elem = $('#image_ph_' + idx);
    parent = elem.parent();
    elem.remove();
    return $('<img>').attr('src', base64).attr('stockIndex',stockindex).attr('id', 'image_ph_' + idx).addClass('news-image').appendTo(parent).on('click', showStockDetail);
};

//放大图片操作
showLargeImage = function() {
    var $this, bounds, imageElem, imageId, imageURL;
    $this = $(this);
    imageElem = $this.get(0);
    imageElem.
    bounds = null;
    if (imageElem != null) {
        bounds = imageElem.getBoundingClientRect();
        bounds.width = imageElem.width;
        bounds.height = imageElem.height;
    }
    imageId = $this.attr('id');
    imageSrc = $this.attr('src');
    imageUrl = $this.attr('imageurl');
    return SNJavascriptBridge.callNativeBlock("loadLargeImage", {
                                              "src": imageSrc,
                                              "id": imageId,
                                              "imageurl": imageUrl,
                                              "bounds": bounds
                                              });
};

//如果是行情图片 跳转行情页面
function showStockDetail(){
    var $this, stockIndex;
    $this = $(this);
    stockIndex = $this.attr('stockIndex');
    return SNJavascriptBridge.callNativeBlock("viewstock_"+stockIndex);
};

loadImage = function(imageurl) {
    return SNJavascriptBridge.callNativeBlock("loadLargeImage", {
                                              "imageurl": imageurl
                                              });
};

loadAd = function(index) {
    return SNJavascriptBridge.callNativeBlock("jumpAdView", {
                                              "index": index
                                              });
};



//资讯正文 table样式
(function (){
 function dealtable (table) {
 var thistable = table;
 var zwtable = document.createElement('div');
 zwtable.className = 'zwtable';
 zwtable.innerHTML = '<div class="tabletip">左右拖动表格，可查看剩余表格内容</div><div class="tablec"><div class="tablemovetipr"><em></em></div><div class="tablemovetipl"><em></em></div><div class="tablecbody"></div></div>';
 thistable.parentNode.replaceChild(zwtable, thistable);
 var tablecbody = zwtable.querySelector('.tablecbody');
 tablecbody.appendChild(thistable);
 var maxscroll = thistable.clientWidth - tablecbody.clientWidth;
 
 if ( maxscroll > 0  ) {
 var tablemovetipr = zwtable.querySelector('.tablemovetipr');
 var tablemovetipl = zwtable.querySelector('.tablemovetipl');
 tablemovetipr.style.height = thistable.clientHeight + 'px';
 tablemovetipl.style.height = thistable.clientHeight + 'px';
 tablemovetipr.style.display = 'block';
 tablecbody.onscroll = function (e){
 if ( tablecbody.scrollLeft >= maxscroll - 8 ) {
 tablemovetipr.style.display = 'none';
 }
 else{
 tablemovetipr.style.display = 'block';
 }
 if ( tablecbody.scrollLeft < 8 ) {
 tablemovetipl.style.display = 'none';
 }
 else{
 tablemovetipl.style.display = 'block';
 }
 }
 }
 else{
 zwtable.querySelector('.tabletip').style.display = 'none';
 }
 }
 
 var tables = document.querySelector('article').querySelectorAll('table');
 for (var i = 0; i < tables.length; i++) {
 dealtable(tables[i]);
 }
 
 })();
